//
// This file was generated by the Eclipse Implementation of JAXB, v4.0.5 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
//


package ru.nsu.khlebnikov.schema;

import jakarta.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the generated package. 
 * <p>An ObjectFactory allows you to programmatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: generated
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link People }
     * 
     * @return
     *     the new instance of {@link People }
     */
    public People createPeople() {
        return new People();
    }

    /**
     * Create an instance of {@link PersonType }
     * 
     * @return
     *     the new instance of {@link PersonType }
     */
    public PersonType createPersonType() {
        return new PersonType();
    }

    /**
     * Create an instance of {@link IdRef }
     * 
     * @return
     *     the new instance of {@link IdRef }
     */
    public IdRef createIdRef() {
        return new IdRef();
    }

    /**
     * Create an instance of {@link SiblingsType }
     * 
     * @return
     *     the new instance of {@link SiblingsType }
     */
    public SiblingsType createSiblingsType() {
        return new SiblingsType();
    }

    /**
     * Create an instance of {@link ChildrenType }
     * 
     * @return
     *     the new instance of {@link ChildrenType }
     */
    public ChildrenType createChildrenType() {
        return new ChildrenType();
    }

    /**
     * Create an instance of {@link SpouceType }
     * 
     * @return
     *     the new instance of {@link SpouceType }
     */
    public SpouceType createSpouceType() {
        return new SpouceType();
    }

    /**
     * Create an instance of {@link ParentsType }
     * 
     * @return
     *     the new instance of {@link ParentsType }
     */
    public ParentsType createParentsType() {
        return new ParentsType();
    }

}
